package info.fanfou.db.dao.mapper;

import info.fanfou.db.entity.UserRole;
import info.fanfou.db.entity.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int deleteByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    UserRole selectByPrimaryKey(Long userRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    int updateByPrimaryKey(UserRole record);
}