package info.fanfou.db.entity;

import java.io.Serializable;
import java.util.Date;

public class Goods implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS.GOODS_ID
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Long goodsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS.PRICE
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS.CREATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Date createdDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS.UPDATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Date updatedDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table GOODS
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Goods(Long goodsId, Float price, Date createdDatetime, Date updatedDatetime) {
        this.goodsId = goodsId;
        this.price = price;
        this.createdDatetime = createdDatetime;
        this.updatedDatetime = updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Goods() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS.GOODS_ID
     *
     * @return the value of GOODS.GOODS_ID
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS.GOODS_ID
     *
     * @param goodsId the value for GOODS.GOODS_ID
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS.PRICE
     *
     * @return the value of GOODS.PRICE
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS.PRICE
     *
     * @param price the value for GOODS.PRICE
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS.CREATED_DATETIME
     *
     * @return the value of GOODS.CREATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS.CREATED_DATETIME
     *
     * @param createdDatetime the value for GOODS.CREATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS.UPDATED_DATETIME
     *
     * @return the value of GOODS.UPDATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS.UPDATED_DATETIME
     *
     * @param updatedDatetime the value for GOODS.UPDATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }
}