package info.fanfou.db.entity;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_ID
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.USER_NAME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.EMAIL
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CREATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Date createdDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.UPDATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private Date updatedDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public User(Long userId, String userName, String email, Date createdDatetime, Date updatedDatetime) {
        this.userId = userId;
        this.userName = userName;
        this.email = email;
        this.createdDatetime = createdDatetime;
        this.updatedDatetime = updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public User() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_ID
     *
     * @return the value of USER.USER_ID
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_ID
     *
     * @param userId the value for USER.USER_ID
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.USER_NAME
     *
     * @return the value of USER.USER_NAME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.USER_NAME
     *
     * @param userName the value for USER.USER_NAME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.EMAIL
     *
     * @return the value of USER.EMAIL
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.EMAIL
     *
     * @param email the value for USER.EMAIL
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.CREATED_DATETIME
     *
     * @return the value of USER.CREATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.CREATED_DATETIME
     *
     * @param createdDatetime the value for USER.CREATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.UPDATED_DATETIME
     *
     * @return the value of USER.UPDATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.UPDATED_DATETIME
     *
     * @param updatedDatetime the value for USER.UPDATED_DATETIME
     *
     * @mbggenerated Thu Aug 20 23:39:47 CST 2015
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }
}