package info.fanfou.db.entity;

import java.io.Serializable;
import java.util.Date;

public class UserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    private Long userRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.USER_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.CREATED_DATETIME
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    private Date createdDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_ROLE.UPDATED_DATETIME
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    private Date updatedDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public UserRole(Long userRoleId, Long userId, Long roleId, Date createdDatetime, Date updatedDatetime) {
        this.userRoleId = userRoleId;
        this.userId = userId;
        this.roleId = roleId;
        this.createdDatetime = createdDatetime;
        this.updatedDatetime = updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public UserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USER_ROLE_ID
     *
     * @return the value of USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public Long getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USER_ROLE_ID
     *
     * @param userRoleId the value for USER_ROLE.USER_ROLE_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public void setUserRoleId(Long userRoleId) {
        this.userRoleId = userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.USER_ID
     *
     * @return the value of USER_ROLE.USER_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.USER_ID
     *
     * @param userId the value for USER_ROLE.USER_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.ROLE_ID
     *
     * @return the value of USER_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.ROLE_ID
     *
     * @param roleId the value for USER_ROLE.ROLE_ID
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.CREATED_DATETIME
     *
     * @return the value of USER_ROLE.CREATED_DATETIME
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public Date getCreatedDatetime() {
        return createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.CREATED_DATETIME
     *
     * @param createdDatetime the value for USER_ROLE.CREATED_DATETIME
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_ROLE.UPDATED_DATETIME
     *
     * @return the value of USER_ROLE.UPDATED_DATETIME
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public Date getUpdatedDatetime() {
        return updatedDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_ROLE.UPDATED_DATETIME
     *
     * @param updatedDatetime the value for USER_ROLE.UPDATED_DATETIME
     *
     * @mbggenerated Wed Aug 19 22:10:21 CST 2015
     */
    public void setUpdatedDatetime(Date updatedDatetime) {
        this.updatedDatetime = updatedDatetime;
    }
}